name: NodeJS Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - "16.x"
          - "18.x"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test the Code
        run: |
          npm install
          npm test
